package org.sleepless_artery.phone_contact_manager.infrastructure.logging;


public enum LogEvent {

    CONTACT_FETCH_STARTED,
    CONTACT_FETCH_SUCCESS,
    CONTACT_FETCH_FAILED,
    CONTACT_NOT_FOUND,

    CONTACT_CREATION_STARTED,
    CONTACT_CREATION_SUCCESS,
    CONTACT_CREATION_FAILED,
    CONTACT_ALREADY_EXISTS,

    CONTACT_UPDATE_STARTED,
    CONTACT_UPDATE_FAILED,
    CONTACT_UPDATE_SUCCESS,

    CONTACT_DELETION_STARTED,
    CONTACT_DELETION_FAILED,
    CONTACT_DELETION_SUCCESS,

    CONTACT_COMPLETE_DELETION_STARTED
}
